### ISSUE TITLE
[Bug]: Can't right click terminal tab to change themes

### ISSUE THREAD

**Issue by Lizardbutt** [wavetermdev/waveterm#1392]
### Current Behavior

When launching a new session on a fresh install, it's sometimes impossible to right click on a tab to access the context menu for that tab

![image](https://github.com/user-attachments/assets/05351923-1c5e-43b5-998b-386fc6a3aee6)

### Expected Behavior

Right click on a tab within the application allows context menu to appear to display options for that tab

![image](https://github.com/user-attachments/assets/b15c85f1-79b5-4871-becd-9d7975cdd9b0)

### Steps To Reproduce

1. Install Wave terminal
2. Open Wave terminal
3. Right click tab to open context menu

### Wave Version

0.9.3

### Platform

Windows

### OS Version/Distribution

Win 10

### Architecture

x64

### Anything else?

Control + Shift + R to force a refresh yields no results.

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Lizardbutt** [comment]
Question - Why is this being marked as `need more info`? What additional information is required?

**Comment by Lizardbutt** [comment]
I mismarked the architecture version for this bug - I've updated it accordingly to `x64`.

**Comment by esimkowitz** [comment]
was marked needs more info because of the arm64 confusion, thanks for correcting this

**Comment by esimkowitz** [comment]
I think we've tracked down the issue, should be fixed now

**Comment by esimkowitz** [comment]
leaving open for now until we get confirmation that this is fixed

**Comment by Lizardbutt** [comment]
> I think we've tracked down the issue, should be fixed in the latest beta (0.10.0-beta.1), could you give it a try @Lizardbutt?

Have changes been pushed? My local copy is reporting there are zero updates available.

![image](https://github.com/user-attachments/assets/84c7bc0e-dd5a-4faf-b482-9d334d4b6929)

![image](https://github.com/user-attachments/assets/2d9b030b-52c6-465c-9521-beddc5dfbff8)

**Comment by Lizardbutt** [comment]
Nevermind, I needed to edit my `settings.json` - I'm checking now.

**Comment by Lizardbutt** [comment]
@esimkowitz functionality works as the original bug posted. Still does not work as intended 😞

**Comment by esimkowitz** [comment]
Hmm is there anything special about your system or your mouse? Are you running in a VM?

**Comment by Lizardbutt** [comment]
> Hmm is there anything special about your system or your mouse? Are you running in a VM?

No - There's nothing special about my system. 

I'm using a Logitech G502 Hero, which shouldn't create any problems - The keyboard I'm using is a Sofle Choc with QMK firmware, I can affirm that there's nothing weird there as I'm not using tap dancing, or any kind of scripting in my profile; I'm not running in a VM either.

**Comment by esimkowitz** [comment]
How often does this happen? Is it every time you right-click you're unable to bring up the menu or is it less frequent? Do you notice any patterns for when it occurs?

**Comment by esimkowitz** [comment]
Also do you see anything unusual in your logs? You can find the log file at `%LOCALUSERDATA%\waveterm\Data\waveapp.log`

**Comment by esimkowitz** [comment]
Okay @Lizardbutt we _think_ we've tracked this one down, and it seems so obvious in retrospect: #1493

We're cutting a new beta build now, I'll post here when it's published

**Comment by esimkowitz** [comment]
@Lizardbutt can you give this release a try and see if it fixes the issue for you? https://github.com/wavetermdev/waveterm/releases/tag/v0.10.0-beta.5

**Comment by esimkowitz** [comment]
I haven't heard back in a while, I believe this is resolved

**Comment by Lizardbutt** [comment]
Issue seems to be fixed! I'll update if this happens again, thank you @esimkowitz !
